# Generated by Django 2.2.3 on 2019-07-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_auto_20190720_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
