# Generated by Django 2.2.3 on 2019-07-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_userphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
