# Generated by Django 2.2.3 on 2019-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0012_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='user_photo',
            field=models.ImageField(default='/none.png', upload_to=''),
        ),
    ]
