# Generated by Django 2.2.3 on 2019-07-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0013_auto_20190722_1615'),
        ('myprofile', '0013_auto_20190724_1156'),
    ]

    operations = [
    ]
