# Generated by Django 2.2.3 on 2019-07-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='frist_field',
            new_name='first_field',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='second_filed',
            new_name='second_field',
        ),
    ]
