# Generated by Django 2.2.7 on 2019-12-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
