# Generated by Django 2.2.3 on 2019-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0003_remove_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='second_field',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sum_field',
        ),
        migrations.AddField(
            model_name='photo',
            name='second_filed',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
