# Generated by Django 2.2.3 on 2019-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0005_auto_20190724_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='first_field',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='second_field',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
