# Generated by Django 2.2.3 on 2019-07-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0006_auto_20190724_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
