# Generated by Django 2.2.3 on 2019-07-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0013_auto_20190728_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
