# Generated by Django 2.2.3 on 2019-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0014_remove_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.CharField(max_length=1000),
        ),
    ]
