# Generated by Django 2.2.3 on 2019-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetry', '0016_remove_photo_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
