# Generated by Django 2.1.1 on 2019-07-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=20)),
                ('size', models.IntegerField(max_length=3600)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('e_mail', models.EmailField(max_length=254)),
                ('users_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_key',
            field=models.ManyToManyField(help_text='Select user for this photo', to='main.User'),
        ),
    ]
