# Generated by Django 2.1.1 on 2019-07-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_users_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_key',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
