# Generated by Django 2.1.1 on 2019-07-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_auto_20190702_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('profile_photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
