# Generated by Django 2.2.3 on 2019-07-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='profile_photo',
        ),
    ]
