# Generated by Django 2.2.3 on 2019-07-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_human_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
    ]
